### ISSUE TITLE
Light mode export and shadows

### ISSUE THREAD

**Issue by gcoan** [pacemaker82/PredBat-Table-Card#10]
New light mode is a great improvement but I can't read the export figures and it looks like status through to cost columns have an embossed style attached to them?
![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/142018870/574fb7cb-7b82-4d66-8898-880db9507b89)

**Comment by pacemaker82** [comment]
Ah so I think the export thing is due to the other octopus card clash again... should be an easy fix. Works ok here without the other card in play:
<img width="621" alt="Screenshot 2024-03-01 at 09 57 18" src="https://github.com/pacemaker82/PredBat-Table-Card/assets/157808562/c5de66ea-bef2-4f2c-9ef0-749f6109e222">

I added the drop shadow to the text because without it the text was unreadable (due to the light colours used by trefor - I pull them across without manipulation). I will see if there's something I can do to make them lighter

**Comment by pacemaker82** [comment]
Actually I believe the issue was that your export "colour" in trefor's plan was white, and I was doing some overrides there to suport the light/dark mode. Version 1.1.1 is out not and hopefully resolves it.

**Comment by gcoan** [comment]
That fixes the unreadable export colours thanks

Yes I see the problem with SoC etc colours.  Trefor's plan had the positive/negative/relative value with black text on a coloured background, your plan has a common background colour and coloured text,  and things like yellow and red text won't show up properly.

I'm not a great fan of the drop shadow though.

But at least its readable now

![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/142018870/2f656e6d-ba90-4283-a398-65396fdb1dc3)

**Comment by gcoan** [comment]
And yes, I have Trefor's plan, yours and Octopus rate card all on the same dashboard tab.  The Octopus one I occasionally look at to see what the actual rates are without overrides such as power up events

**Comment by pacemaker82** [comment]
I've updated it to be much better (to my eyes at least), version 1.1.2 is out.

**Comment by gcoan** [comment]
Much better now.   I quite like this

Looks like the shadows are only the battery charge and discharge icons, not the rest of the text

**Comment by pacemaker82** [comment]
yeah I left the drop shadow on the battery icons because it helped them pop out a bit against the background row colours. Will keep assessing

**Comment by pacemaker82** [comment]
going to remove the shadows in the next release as after testing the icons looks OK on the new table rows for light mode

**Comment by pacemaker82** [comment]
Fixed
