### ISSUE TITLE
Force discharge unreadable in dark mode

### ISSUE THREAD

**Issue by gcoan** [pacemaker82/PredBat-Table-Card#26]
White text on yellow background 

![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/142018870/a4b449c5-0772-48c2-8315-bad9e6f6571f)

**Comment by pacemaker82** [comment]
should now be fixed in https://github.com/pacemaker82/PredBat-Table-Card/releases/tag/v1.5.3.5

**Comment by gcoan** [comment]
Agreed, discharge now readable

But.... should Charge in the split slot be coloured green as it is in the full slot?

![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/142018870/952fc758-8ad2-47f4-845b-6d5b47532354)

Just noticed the split slot charge is also the (white) background colour in light mode
![image](https://github.com/pacemaker82/PredBat-Table-Card/assets/142018870/4fe35ad5-7c88-4dea-a8d7-3fbaa4b4191a)

**Comment by pacemaker82** [comment]
> should Charge in the split slot be coloured green as it is in the full slot?

No because that actually should say "charging" because its doing that from solar (i.e. not forced by Predbat). On the original table it'll just show an arrow up with a non coloured background, suggesting the same ... "idle" charge or eco mode charge. The coloured ones are planned by predbat (same as the predbat table) - unless you are seeing it green there and white here.

> Just noticed the split slot charge is also the (white) background colour in light mode

Its white because the whole row is white.

**Comment by pacemaker82** [comment]
Fixed in 1.5.3.6 https://github.com/pacemaker82/PredBat-Table-Card/releases/tag/v1.5.3.6

**Comment by gcoan** [comment]
thanks, that fixes it.  It was indeed a solar charge not a forced charge
